services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    depends_on:
      - mysql
      - tomcat

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-password_root}"
      MYSQL_DATABASE: "${DB_DATABASE:-database}"
      MYSQL_USER: "${DB_USER:-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-password}"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  tomcat:
    image: tomcat:10-jdk11
    restart: unless-stopped
    user: root
    ports:
      - "${TOMCAT_PORT:-8080}:8080"
    volumes:
      - ../build:/usr/local/tomcat/webapps
    depends_on:
      - mysql

volumes:
  mysql-data:
