name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite criar releases e tags
      issues: write # Permite comentar em issues
      pull-requests: write # Permite comentar em PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create build directory
        run: mkdir build

      - name: Build project
        run: npm run build

      - name: Package build
        run: |
          cd build
          zip -r ../eniac-projeto-build.zip .

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: semantic-release-bot
          GIT_AUTHOR_EMAIL: semantic-release-bot@github.com
          GIT_COMMITTER_NAME: semantic-release-bot
          GIT_COMMITTER_EMAIL: semantic-release-bot@github.com
        run: npx semantic-release

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Release Asset
        uses: actions/download-release-asset@v2
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          asset_name: eniac-projeto.war
          github_token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
      - name: Clear Remote Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -rf ${{ secrets.REMOTE_PATH }}/eniac-projeto/*
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "eniac-projeto.war"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}